<?php

/**
 * This is the model base class for the table "tbl_room_option".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "RoomOption".
 *
 * Columns in table "tbl_room_option" available as properties of the model,
 * followed by relations of table "tbl_room_option" available as properties of the model.
 *
 * @property integer $id
 * @property integer $room_id
 * @property string $description
 * @property integer $price
 * @property integer $option_id
 *
 * @property Room $room
 * @property Option $option
 */
abstract class BaseRoomOption extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_room_option';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'RoomOption|RoomOptions', $n);
	}

	public static function representingColumn() {
		return 'description';
	}

	public function rules() {
		return array(
			array('price, option_id', 'required'),
			array('price, option_id', 'numerical', 'integerOnly'=>true),
			array('description', 'length', 'max'=>255),
			array('id, room_id, description, price, option_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'room' => array(self::BELONGS_TO, 'Room', 'room_id'),
			'option' => array(self::BELONGS_TO, 'Option', 'option_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	/**
	 * Prepares create_user_id and update_user_id attributes before
	 saving.
	 */
	protected function beforeSave()
	{
	  if(null !== Yii::app()->user)
	    $id=Yii::app()->user->id;
	  else
	    $id=1;
	  if($this->isNewRecord)
	    $this->create_user_id=$id;
	  $this->update_user_id=$id;
	  return parent::beforeSave();
	}
	
	
	public function behaviors()
	{
	  return array(
	    'CTimestampBehavior' => array(
	      'class' => 'zii.behaviors.CTimestampBehavior',
	      'createAttribute' => 'create_time',
	      'updateAttribute' => 'update_time',
	      'setUpdateOnCreate' => true,
	    ),
	  );
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('room_id', $this->room_id);
		$criteria->compare('description', $this->description, true);
		$criteria->compare('price', $this->price);
		$criteria->compare('option_id', $this->option_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}