<?php

/**
 * This is the model base class for the table "tbl_room_image".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "RoomImage".
 *
 * Columns in table "tbl_room_image" available as properties of the model,
 * followed by relations of table "tbl_room_image" available as properties of the model.
 *
 * @property integer $id
 * @property string $caption
 * @property string $content
 * @property string $filename
 * @property integer $room_id
 * @property string $create_time
 * @property integer $create_user_id
 * @property string $update_time
 * @property integer $update_user_id
 *
 * @property Room $room
 */
abstract class BaseRoomImage extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_room_image';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'RoomImage|RoomImages', $n);
	}

	public static function representingColumn() {
		return 'filename';
	}

	public function rules() {
		return array(
			//array('room_id', 'required'),
			array('room_id, create_user_id, update_user_id', 'numerical', 'integerOnly'=>true),
			array('caption, filename', 'length', 'max'=>255),
			array('content, create_time, update_time', 'safe'),
		  array('filename', 'file','types'=>'jpg, gif, png', 'allowEmpty'=>true, 'on'=>'insert,update'),
			array('caption, content, create_time, create_user_id, update_time, update_user_id', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, caption, content, filename, room_id, create_time, create_user_id, update_time, update_user_id', 'safe', 'on'=>'search'),
		);
	}


	/**
	 * Prepares create_user_id and update_user_id attributes before
	 saving.
	 */
	protected function beforeSave()
	{
	  if(null !== Yii::app()->user)
	    $id=Yii::app()->user->id;
	  else
	    $id=1;
	  if($this->isNewRecord)
	    $this->create_user_id=$id;
	  $this->update_user_id=$id;
	  return parent::beforeSave();
	}
	
	
	public function behaviors()
	{
	  return array(
	    'CTimestampBehavior' => array(
	      'class' => 'zii.behaviors.CTimestampBehavior',
	      'createAttribute' => 'create_time',
	      'updateAttribute' => 'update_time',
	      'setUpdateOnCreate' => true,
	    ),
	  );
	}
	
	
	public function relations() {
		return array(
			'room' => array(self::BELONGS_TO, 'Room', 'room_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'caption' => Yii::t('app', 'Caption'),
			'content' => Yii::t('app', 'Content'),
			'filename' => Yii::t('app', 'Filename'),
			'room_id' => null,
			'create_time' => Yii::t('app', 'Create Time'),
			'create_user_id' => Yii::t('app', 'Create User'),
			'update_time' => Yii::t('app', 'Update Time'),
			'update_user_id' => Yii::t('app', 'Update User'),
			'room' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('caption', $this->caption, true);
		$criteria->compare('content', $this->content, true);
		$criteria->compare('filename', $this->filename, true);
		$criteria->compare('room_id', $this->room_id);
		$criteria->compare('create_time', $this->create_time, true);
		$criteria->compare('create_user_id', $this->create_user_id);
		$criteria->compare('update_time', $this->update_time, true);
		$criteria->compare('update_user_id', $this->update_user_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}